services:

  server:
    build:
      context: ./node
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: ./postgres
    restart: always
    user: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pwd
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data:
