##
#
#  Copyright Hans de Rooij 2024
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, 
#  software distributed under the License is distributed on an 
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
#  either express or implied. See the License for the specific 
#  language governing permissions and limitations under the 
#  License.
#
##

ARG NODE_VER=18.20
ARG PLATFORM_VER=alpine3.19

FROM node:${NODE_VER}-${PLATFORM_VER}

# App directory
WORKDIR /usr/src/app/

# Install app dependencies
COPY package*.json ./
RUN npm install --omit=dev

# Deliver source code
COPY src/ ./src/

# Start application
CMD [ "npm", "run", "prod" ]
